In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df=pd.read_csv('dataset_rh_churn_renomme.csv')
df.head()

,age,anciennete_annees,salaire_mensuel_k,heures_travail_hebdo,score_performance,absences_annuelles,niveau_etude,departement,sexe,churn
0,66.137113,61.728612,42.687987,75.703652,73.926341,93.686032,Low,Sales,Female,Yes
1,54.446027,52.906862,57.813467,68.873715,71.247521,68.365638,High,Sales,NaN,No
2,35.862855,66.925075,79.412174,69.935602,61.813950,76.396537,Low,Tech,Male,Yes
3,55.947543,52.659801,NaN,74.863765,62.338792,73.380452,Medium,HR,Other,Yes
4,45.602689,56.467930,53.644422,69.201915,50.859399,89.419424,Low,Sales,Other,No

In [3]:
df.dtypes

age                     float64
anciennete_annees       float64
salaire_mensuel_k       float64
heures_travail_hebdo    float64
score_performance       float64
absences_annuelles      float64
niveau_etude             object
departement              object
sexe                     object
churn                    object
dtype: object

In [4]:
df.isna().sum()

age                     52
anciennete_annees       53
salaire_mensuel_k       51
heures_travail_hebdo    55
score_performance       52
absences_annuelles      53
niveau_etude            53
departement             56
sexe                    54
churn                    0
dtype: int64

In [5]:
df.duplicated().sum()

np.int64(50)

In [6]:
df.columns

Index(['age', 'anciennete_annees', 'salaire_mensuel_k', 'heures_travail_hebdo',
       'score_performance', 'absences_annuelles', 'niveau_etude',
       'departement', 'sexe', 'churn'],
      dtype='object')

In [9]:
df.departement

0         Sales
1         Sales
2          Tech
3            HR
4         Sales
         ...
1045      Sales
1046    Finance
1047         HR
1048        NaN
1049      Sales
Name: departement, Length: 1050, dtype: object

In [10]:
df['churn'].unique()

array(['Yes', 'No'], dtype=object)

In [11]:
df.dtypes

age                     float64
anciennete_annees       float64
salaire_mensuel_k       float64
heures_travail_hebdo    float64
score_performance       float64
absences_annuelles      float64
niveau_etude             object
departement              object
sexe                     object
churn                    object
dtype: object

In [12]:
df.isna().sum()

age                     52
anciennete_annees       53
salaire_mensuel_k       51
heures_travail_hebdo    55
score_performance       52
absences_annuelles      53
niveau_etude            53
departement             56
sexe                    54
churn                    0
dtype: int64

In [13]:
df.age.fillna(df.age.mean(),inplace=True) ##inplace=true remplacer et appliquer dans le jeu de donnees

C:\Users\NICK-TECH\AppData\Local\Temp\ipykernel_22624\153029414.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df.age.fillna(df.age.mean(),inplace=True) ##inplace=true remplacer et appliquer dans le jeu de donnees

In [14]:
df.anciennete_annees.fillna(df.anciennete_annees.mean(),inplace=True)

C:\Users\NICK-TECH\AppData\Local\Temp\ipykernel_22624\507312037.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df.anciennete_annees.fillna(df.anciennete_annees.mean(),inplace=True)

In [15]:
df.salaire_mensuel_k.fillna(df.salaire_mensuel_k.mean(),inplace=True)

C:\Users\NICK-TECH\AppData\Local\Temp\ipykernel_22624\1540299850.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df.salaire_mensuel_k.fillna(df.salaire_mensuel_k.mean(),inplace=True)

In [16]:
df.heures_travail_hebdo.fillna(df.heures_travail_hebdo.mean(),inplace=True)

C:\Users\NICK-TECH\AppData\Local\Temp\ipykernel_22624\3452907996.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df.heures_travail_hebdo.fillna(df.heures_travail_hebdo.mean(),inplace=True)

In [17]:
df.score_performance.fillna(df.score_performance.mean(),inplace=True)

C:\Users\NICK-TECH\AppData\Local\Temp\ipykernel_22624\461499158.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df.score_performance.fillna(df.score_performance.mean(),inplace=True)

In [18]:
df.absences_annuelles.fillna(df.absences_annuelles.mean(),inplace=True)

C:\Users\NICK-TECH\AppData\Local\Temp\ipykernel_22624\571306726.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df.absences_annuelles.fillna(df.absences_annuelles.mean(),inplace=True)

In [19]:
df.dtypes

age                     float64
anciennete_annees       float64
salaire_mensuel_k       float64
heures_travail_hebdo    float64
score_performance       float64
absences_annuelles      float64
niveau_etude             object
departement              object
sexe                     object
churn                    object
dtype: object

In [21]:
df['departement'].unique()

array(['Sales', 'Tech', 'HR', 'Finance'], dtype=object)

In [20]:
df.departement.fillna(df.departement.mode()[0],inplace=True)

In [22]:
df.niveau_etude.fillna(df.niveau_etude.mode()[0],inplace=True)

C:\Users\NICK-TECH\AppData\Local\Temp\ipykernel_22624\141413758.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df.niveau_etude.fillna(df.niveau_etude.mode()[0],inplace=True)

In [23]:
df.sexe.fillna(df.sexe.mode()[0],inplace=True)

C:\Users\NICK-TECH\AppData\Local\Temp\ipykernel_22624\4121893722.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df.sexe.fillna(df.sexe.mode()[0],inplace=True)

In [24]:
df.isna().sum()

age                     0
anciennete_annees       0
salaire_mensuel_k       0
heures_travail_hebdo    0
score_performance       0
absences_annuelles      0
niveau_etude            0
departement             0
sexe                    0
churn                   0
dtype: int64

In [25]:
df

,age,anciennete_annees,salaire_mensuel_k,heures_travail_hebdo,score_performance,absences_annuelles,niveau_etude,departement,sexe,churn
0,66.137113,61.728612,42.687987,75.703652,73.926341,93.686032,Low,Sales,Female,Yes
1,54.446027,52.906862,57.813467,68.873715,71.247521,68.365638,High,Sales,Female,No
2,35.862855,66.925075,79.412174,69.935602,61.813950,76.396537,Low,Tech,Male,Yes
3,55.947543,52.659801,59.936597,74.863765,62.338792,73.380452,Medium,HR,Other,Yes
4,45.602689,56.467930,53.644422,69.201915,50.859399,89.419424,Low,Sales,Other,No
...,...,...,...,...,...,...,...,...,...,...
1045,48.093176,49.558860,48.382162,76.460301,65.193521,85.409542,Low,Sales,Other,No
1046,50.340835,46.012160,64.413072,66.642948,64.001780,80.374120,Medium,Finance,Female,No
1047,51.024224,51.661805,55.757637,63.699397,59.822357,49.777221,Low,HR,Female,Yes
1048,58.502217,50.498107,57.514714,61.943809,84.780719,88.366574,Medium,Tech,Female,No
1049,50.242195,73.093063,55.030680,73.139809,77.864062,64.009608,High,Sales,Male,Yes

In [26]:
df.duplicated().sum()

np.int64(50)

In [27]:
df.drop_duplicates(inplace=True)

In [28]:
#10-Traitement des outliers
# Fonction pour détecter et remplacer les valeurs aberrantes avec les Bounds
def replace_outliers(data):
    for col in data.select_dtypes(include=['number']).columns:  # Only process numeric columns
        Q1 = data[col].quantile(0.25)
        Q3 = data[col].quantile(0.75)
        IQR = Q3 - Q1
        lower_bound = Q1 - 1.5 * IQR
        upper_bound = Q3 + 1.5 * IQR
        data[col] = np.where(data[col] < lower_bound, lower_bound, data[col])
        data[col] = np.where(data[col] > upper_bound, upper_bound, data[col])

In [29]:
replace_outliers(df)

In [30]:
##13)encodage des variables categhorielles en binaire
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df.niveau_etude=le.fit_transform(df.niveau_etude)
df.departement=le.fit_transform(df.departement)
df.sexe=le.fit_transform(df.sexe)
df.churn=le.fit_transform(df.churn)
df.head()

,age,anciennete_annees,salaire_mensuel_k,heures_travail_hebdo,score_performance,absences_annuelles,niveau_etude,departement,sexe,churn
0,66.137113,61.728612,42.687987,75.703652,73.926341,93.686032,1,2,0,1
1,54.446027,52.906862,57.813467,68.873715,71.247521,68.365638,0,2,0,0
2,35.862855,66.925075,79.412174,69.935602,61.813950,76.396537,1,3,1,1
3,55.947543,52.659801,59.936597,74.863765,62.338792,73.380452,2,1,2,1
4,45.602689,56.467930,53.644422,69.201915,50.859399,89.419424,1,2,2,0

In [31]:
df.dtypes

age                     float64
anciennete_annees       float64
salaire_mensuel_k       float64
heures_travail_hebdo    float64
score_performance       float64
absences_annuelles      float64
niveau_etude              int64
departement               int64
sexe                      int64
churn                     int64
dtype: object

In [32]:
df.duplicated().sum()

np.int64(0)